language: cpp
compiler:
 - gcc

before_install:
 - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-add-repository -y ppa:beineri/opt-qt562
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt56base qt56tools g++-5
 - source /opt/qt56/bin/qt56-env.sh
 - export CXX="g++-5"
 - export CC="gcc-5"

script:
 - qmake --version
 - $CXX --version
 - ./build.sh
 - ./test.sh
