dist: xenial

language: cpp
compiler:
 - gcc

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt571-xenial'
    packages:
      - qt57base
      - qt57tools
      - qt57websockets
      - cmake

before_install:
 - source /opt/qt57/bin/qt57-env.sh

script:
 - ctest --verbose --build-and-test . build-default --build-generator "Unix Makefiles" --test-command ctest -V
 - ctest --verbose --build-and-test . build-no-sll --build-generator "Unix Makefiles" --build-options -DQMQTT_SUPPORT_SSL=OFF --test-command ctest -V
 - ctest --verbose --build-and-test . build-websockets --build-generator "Unix Makefiles" --build-options -DQMQTT_SUPPORT_WEBSOCKETS=ON --test-command ctest -V
 - ctest --verbose --build-and-test . build-example --build-generator "Unix Makefiles" --build-options -DQMQTT_BUILD_EXAMPLE=ON --test-command ctest -V
 - ctest --verbose --build-and-test . build-no-test --build-generator "Unix Makefiles" --build-options -DBUILD_TESTING=OFF
